import { MemoryEntry, Message } from '../types';
import { db, auth } from '../lib/firebase';
import { collection, doc, getDocs, setDoc, deleteDoc, query, orderBy, where } from 'firebase/firestore';

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null): never {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  }
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// --- Long Term Memory (Facts) ---

export const getMemory = async (uid: string): Promise<MemoryEntry[]> => {
  if (!uid) return [];
  const path = `users/${uid}/memories`;
  try {
    const q = query(collection(db, path), where('userId', '==', uid), orderBy('timestamp', 'asc'));
    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => doc.data() as MemoryEntry);
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
  }
};

export const saveMemory = async (uid: string, content: string): Promise<boolean> => {
  if (!uid) return false;
  try {
    const memories = await getMemory(uid);
    if (!memories.some(m => m.content === content.trim())) {
      const newEntry: MemoryEntry = {
        userId: uid,
        content: content.trim(),
        timestamp: Date.now()
      };
      // We use document ID generated by Date.now().toString() for simplicity
      // and match ID requirement (isValidId checks string matching ^[a-zA-Z0-9_\-]+$)
      const newId = `mem_` + Date.now().toString() + '_' + Math.random().toString(36).substr(2, 5);
      const path = `users/${uid}/memories/${newId}`;
      try {
        await setDoc(doc(db, `users/${uid}/memories`, newId), newEntry);
        return true;
      } catch (error) {
        handleFirestoreError(error, OperationType.WRITE, path);
      }
    }
    return false;
  } catch (error) {
    console.error("Falha ao gravar memória:", error);
    return false;
  }
};

export const clearMemory = async (uid: string) => {
  if (!uid) return;
  const path = `users/${uid}/memories`;
  try {
    const q = query(collection(db, path), where('userId', '==', uid));
    const snapshot = await getDocs(q);
    for (const d of snapshot.docs) {
      await deleteDoc(d.ref);
    }
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, path);
  }
};

export const getMemoryContextString = async (uid: string): Promise<string> => {
  const memories = await getMemory(uid);
  if (memories.length === 0) return "BANCO DE DADOS: Vazio.";
  
  return `BANCO DE DADOS (MEMÓRIA PERSISTENTE DO USUÁRIO):\n${memories.map(m => `- ${m.content}`).join('\n')}`;
};

// --- Session History (Context Preservation) ---

export const getHistory = async (uid: string): Promise<Message[]> => {
  if (!uid) return [];
  const path = `users/${uid}/messages`;
  try {
    const q = query(collection(db, path), where('userId', '==', uid), orderBy('timestamp', 'asc'));
    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => {
      const data = doc.data();
      // Omit userId when returning to app context if necessary, or just return as is
      return {
        id: doc.id,
        role: data.role,
        content: data.content,
        timestamp: data.timestamp,
        isHidden: data.isHidden
      };
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
  }
};

export const saveMessageToHistory = async (uid: string, message: Message) => {
  if (!uid) return;
  const docId = `msg_` + message.timestamp.toString() + '_' + Math.random().toString(36).substr(2, 5);
  const path = `users/${uid}/messages/${docId}`;
  
  const dataToSave = {
    userId: uid,
    role: message.role,
    content: message.content,
    timestamp: message.timestamp,
    ...(message.isHidden !== undefined ? { isHidden: message.isHidden } : {})
  };
  
  try {
    await setDoc(doc(db, `users/${uid}/messages`, docId), dataToSave);
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, path);
  }
};

export const clearHistory = async (uid: string) => {
  if (!uid) return;
  const path = `users/${uid}/messages`;
  try {
    const q = query(collection(db, path), where('userId', '==', uid));
    const snapshot = await getDocs(q);
    for (const d of snapshot.docs) {
      await deleteDoc(d.ref);
    }
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, path);
  }
};